version: '3.5'
services:
    database:
        image: mysql
        container_name: mysql
        ports:
        - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: adopet
            # MYSQL_USER: root
            # MYSQL_PASSWORD: root
        volumes:
            - db-volume:/var/lib/mysql
volumes:
    db-volume: