@baseUrl=http://localhost:8080
### TUTOR
POST {{baseUrl}}/tutores
Content-Type: application/json

{
    "nome": "Fulano3",
    "telefone": "(97)8757-1000",
    "email": "fulano3@gmail.com"
}
###
GET {{baseUrl}}/pets

### ADOCAO
POST {{baseUrl}}/adocoes
Content-Type: application/json

{
    "idTutor": 3,
    "idPet": 2,
    "motivo": "Companhia"
}

### ABRIGO
POST {{baseUrl}}/abrigos
Content-Type:application/json

{
    "nome": "PetLove3",
    "telefone": "(94)8757-0944",
    "email": "petlove3@gmail.com"
}

###
GET {{baseUrl}}/abrigos

###
GET {{baseUrl}}/abrigos/1/pets


###
POST {{baseUrl}}/abrigos/1/pets
Content-Type: application/json

{
    "tipo": "CACHORRO",
    "nome": "Bela",
    "raca": "Vira-Lata",
    "idade": 10,
    "cor": "cinza e preto",
    "peso": 5,
    "adotado": false
}

